### ISSUE TITLE
17.09 release todo

### ISSUE THREAD

**Issue by afgane** [galaxyproject/cloudman#73]
17.09 will still be a minor-update release with the following being known issues from earlier releases to be fixed then:

 - [ ] Update IE images being staged
 - [ ] Include `/mnt/galaxy/galaxy-app/config/plugins/interactive_environments/jupyter/config/jupyter.ini` to set `use_volumes = False` (unless error when loading a BAM file is resolved `docker: Error response from daemon: Invalid bind mount spec "/mnt/galaxy/files/000/dataset_9.dat:/import/[9] MergeSamFiles on data 7, data 6, and data 5: Merged BAM dataset.bam:rw": Invalid volume specification: '/mnt/galaxy/files/000/dataset_9.dat:/import/[9] MergeSamFiles on data 7, data 6, and data 5: Merged BAM dataset.bam:rw'.`)
 - [ ] Set `command_inject = -e DEFAULT_CONTAINER_RUNTIME=900` in `jupyter.ini`
 - [ ] Include `/mnt/galaxy/galaxy-app/config/plugins/interactive_environments/rstudio/config/rstudio.ini` and set `use_volumes = False`
 - [ ] Update `galaxy.ini` proxy settings as per https://docs.galaxyproject.org/en/master/admin/interactive_environments.html#configuring-the-proxy
 - [ ] Update nginx's conf (`galaxy.locations`) to fix the incorrect url prefix for IEs (it includes `/galaxy/...`)
 - [ ] Update `conda_channels` in `galaxy.ini` to `iuc,bioconda,conda-forge,defaults,r`

**Comment by nuwang** [comment]
Closing because old version.
